# SAM FILE
AWSTemplateFormatVersion: '2010-09-09'  # versão do CloudFormation
Transform: 'AWS::Serverless-2016-10-31' # Versão odo template SAM usado na Traformação para o CF.
Description: A starter AWS Lambda function.
Resources:
  helloworldpython3:
    Type: 'AWS::Serverless::Function' # Tipo especifico de recurso SAM (tem todos os itens serveless).
    Properties:
      Handler: app.lambda_handler # Função inicial do lamdba
      Runtime: python3.9
      CodeUri: src/  # indica onde esta o codigo na pasta local
      Description: A starter AWS Lambda function.
      MemorySize: 128
      Timeout: 3
      Environment:
        Variables:
          TABLE_NAME: !Ref Table
          REGION_NAME: !Ref AWS::Region
      Events:  ## Permite adicionar integrações
        HelloWorldSAMAPI: ## Criando API gateway
          Type: Api
          Properties:
            Path: /hello
            Method: GET
      Policies:  # Usado para criar polices
        - DynamoDBCrudPolicy:
            TableName: !Ref Table  

  Table:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: greeting
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2