apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: uni-cluster
networking:
  apiServerAddress: "127.0.0.1"
  apiServerPort: 6443
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 8095
    hostPort: 30100
    protocol: TCP
  - containerPort: 80
    hostPort: 30200
    protocol: TCP
- role: worker