name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches:
      - main  # Aciona o deploy ao fazer push na branch main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install

      - name: Construir o site Docusaurus
        run: npm run build

      - name: Implantar no GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GH_PAT }}  # Usando o token personalizado
          publish_dir: ./build
          cname: docs.uniii.com.br  # Define o domínio personalizado
